proc template;
define statgraph sgplot;
dynamic _NEGATIVE_;
dynamic _ticklist_;
begingraph / collation=binary dataColors=( CX33A3FF CX768396 );
EntryTitle halign=left "Top 2 Reasons Why Customers " halign=left textattrs=( color=CX33A3FF weight=bold style=italic) "Prefer" halign=left textattrs=( color=CX768396 weight=bold style=italic size=16pt) " Serentiva" / textattrs=( color=CX768396 size=16pt);
EntryTitle " " / textattrs=(size=GraphLabelText:fontsize);
EntryTitle " " / textattrs=(size=GraphLabelText:fontsize);
layout overlay / walldisplay=none yaxisopts=(discreteOpts=(sortOrder=_InternalData)) xaxisopts=( display=none type=linear ) y2axisopts=(labelFitPolicy=Split) yaxisopts=( reverse=true display=( tickvalues ) labelFitPolicy=Split TickValueAttrs=( Color=CX768396 Size=12pt Weight=bold) type=discrete discreteopts=( sortOrder=_InternalData tickValueList=_ticklist_ ) ) y2axisopts=(labelFitPolicy=Split) y2axisopts=(type=Discrete reverse=true discreteOpts=(tickValueList=_ticklist_ tickValueListPolicy=Union));
   BarChartParm X='Reason'n Y='_Sum1_Pct_'n / primary=true orient=horizontal Group='Top2'n DataLabelAttrs=( Color=CX4F4F4F Size=12pt Weight=bold ) Display=( Fill ) LegendLabel="Pct" DataLabel='percentage'n NAME="HBAR" groupdisplay=cluster;
endlayout;
EntryFootnote textattrs=( style=italic) "N=99" / textattrs=( color=CX768396);
endgraph;
end;
run;
